speech_config:
  sample_rate: 22050
  normalize: True
  preemphasis: 0.97
  feature_bins: 80 ##https://arxiv.org/pdf/1909.06678.pdf
  center: True
  frame_ms: 10
  stride_ms: 5

  input_shape: 2000

model_config:
  batch_size: 32
  vocab_size: 28
  
  prediction_network:
    embedding_size: 450 #random
    num_layers: 8 #https://arxiv.org/pdf/1909.06678.pdf
    lstm_hidden_units: 2048 #https://arxiv.org/pdf/1909.06678.pdf
    lstm_projection: 640 #https://arxiv.org/pdf/1909.06678.pdf

  encoder:
